### ISSUE TITLE
Trusted publishing GitHub Action docs should specify `environment` if there is one

### ISSUE THREAD

**Issue by mschwager** [rubygems/guides#355]
Hi all 👋 

I've been working through the new trusted publishing, and everything seems to be working pretty well. I did notice one thing missing from the docs: the [GitHub Actions](https://guides.rubygems.org/trusted-publishing/releasing-gems/) don't mention including [the `environment`](https://docs.github.com/en/actions/deployment/targeting-different-environments/using-environments-for-deployment#using-an-environment) if there is one. In other words, if you specify an environment when [creating a trusted publisher](https://guides.rubygems.org/trusted-publishing/adding-a-publisher/) you must also specify it in the GitHub Action workflow.

**Comment by woodruffw** [comment]
For context: the equivalent docs on the PyPI side: https://docs.pypi.org/trusted-publishers/using-a-publisher/

Specifically, this is the example we use on PyPI:

```
jobs:
  pypi-publish:
    name: upload release to PyPI
    runs-on: ubuntu-latest
    # Specifying a GitHub environment is optional, but strongly encouraged
    environment: release
    permissions:
      # IMPORTANT: this permission is mandatory for trusted publishing
      id-token: write
    steps:
      # retrieve your distributions here

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
```

This can be closely adapted to RubyGems, so I'll file a PR later today.
